name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg build-essential

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install maturin pytest httpx spotipy transformers torch numpy pydub qdrant-client fastapi uvicorn python-multipart

    - name: Build Rust extension
      run: maturin develop

    - name: Run Tests
      run: pytest tests/